import PDFDocument from 'pdfkit';

export interface GeneratedThesisMandate {
  role: string;
  label: string;
  currency: string;
  objective: string;
  inclusionCriteria: string[];
  exclusionCriteria: string[];
}

export interface GeneratedThesisInput {
  title: string;
  investorName: string;
  purpose: string;
  timeHorizon: string;
  riskTolerance: string;
  markets: string[];
  globalConstraints: string[];
  reviewCadence: string;
  mandates: GeneratedThesisMandate[];
}

function safeText(value: string): string {
  return value.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g, '').trim();
}

function bulletList(document: PDFKit.PDFDocument, items: string[], empty: string): void {
  if (!items.length) {
    document.fillColor('#52606d').text(empty);
    return;
  }
  for (const item of items) {
    document.fillColor('#16202a').text(`• ${safeText(item)}`, { indent: 10, paragraphGap: 4 });
  }
}

function section(document: PDFKit.PDFDocument, heading: string, text?: string): void {
  document.moveDown(0.75).fillColor('#0f3a5b').font('Helvetica-Bold').fontSize(13).text(heading);
  if (text) document.moveDown(0.25).fillColor('#16202a').font('Helvetica').fontSize(10.5).text(safeText(text), { lineGap: 3 });
}

/** A static, text-first PDF so it is safe to pass through the same upload validation as a user document. */
export async function renderGeneratedThesisPdf(input: GeneratedThesisInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const document = new PDFDocument({ size: 'A4', margin: 54, info: { Title: safeText(input.title), Author: 'Portfolio Intelligence' } });
    const chunks: Buffer[] = [];
    document.on('data', (chunk: Buffer) => chunks.push(chunk));
    document.on('end', () => resolve(Buffer.concat(chunks)));
    document.on('error', reject);

    document.rect(0, 0, document.page.width, document.page.height).fill('#f7f4ed');
    document.fillColor('#0f3a5b').font('Helvetica-Bold').fontSize(11).text('PORTFOLIO INTELLIGENCE', 54, 70);
    document.fillColor('#16202a').fontSize(27).text(safeText(input.title), 54, 126, { width: 480, lineGap: 5 });
    document.fillColor('#52606d').font('Helvetica').fontSize(12).text(`Prepared for ${safeText(input.investorName)}`, 54, 220);
    document.fillColor('#0f3a5b').rect(54, 274, 145, 3).fill();
    document.fillColor('#16202a').font('Helvetica').fontSize(11).text('Investment mandate and decision framework', 54, 298);
    document.fillColor('#52606d').fontSize(9.5).text('This document records the investor’s instructions. It is subject to explicit human review before it is used for market research or portfolio decisions.', 54, 672, { width: 480, lineGap: 3 });

    document.addPage();
    document.fillColor('#0f3a5b').font('Helvetica-Bold').fontSize(18).text('Mandate at a glance');
    section(document, 'Investment purpose', input.purpose);
    section(document, 'Time horizon and risk posture');
    document.fillColor('#16202a').font('Helvetica').fontSize(10.5).text(`Time horizon: ${safeText(input.timeHorizon)}\nRisk posture: ${safeText(input.riskTolerance)}\nReview cadence: ${safeText(input.reviewCadence)}`, { lineGap: 4 });
    section(document, 'Markets and geographies');
    bulletList(document, input.markets, 'No market or geography was specified.');
    section(document, 'Portfolio-wide constraints');
    bulletList(document, input.globalConstraints, 'No portfolio-wide constraints were specified.');

    for (const mandate of input.mandates) {
      document.addPage();
      document.fillColor('#0f3a5b').font('Helvetica-Bold').fontSize(18).text(safeText(mandate.label));
      document.fillColor('#52606d').font('Helvetica').fontSize(10).text(`Portfolio identifier: ${safeText(mandate.role)}  ·  Native currency: ${safeText(mandate.currency)}`);
      section(document, 'Objective', mandate.objective);
      section(document, 'What qualifies');
      bulletList(document, mandate.inclusionCriteria, 'No explicit qualifying criteria were supplied.');
      section(document, 'What disqualifies');
      bulletList(document, mandate.exclusionCriteria, 'No explicit disqualifying criteria were supplied.');
    }

    document.addPage();
    document.fillColor('#0f3a5b').font('Helvetica-Bold').fontSize(18).text('Governance and decision protocol');
    section(document, 'Use of this thesis', 'This thesis guides research and review. It does not authorise a trade or add a security to a portfolio. Every candidate requires evidence-based review and an explicit investment decision.');
    section(document, 'Review discipline', 'Reassess the thesis at the stated cadence and whenever a material change affects objectives, constraints, time horizon, liquidity needs, or risk capacity. Record amendments as a new thesis version.');
    document.fillColor('#52606d').font('Helvetica').fontSize(9).text('Generated by Portfolio Intelligence. This document is an investor mandate, not investment advice or a solicitation to transact.', 54, 690, { width: 480, lineGap: 3 });
    document.end();
  });
}

export function generatedThesisFileName(title: string): string {
  const stem = safeText(title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 80) || 'investment-thesis';
  return `${stem}-investment-thesis.pdf`;
}
